feat: Toggle, RadioButton, CheckBox 컴포넌트 추가
Wraffle-Inc/wraffle pull request #12
Opened 2024-08-10 18:12 UTC by eric-hjh

## 📖 개요

## 💻 작업사항

- CheckBox 컴포넌트
- RadioButton, Group 컴포넌트
- Switch 컴포넌트
3개 공통 컴포넌트 추가 및 스토리북 작성

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-14 10:55 UTC, sangminlee98 requested changes
리뷰 확인 부탁드립니다 🙇‍♂️
그리고 혹시 pnpm 버전이 9.5.0이 맞을까요?? `pnpm i` 명령어 입력하니 lock파일이 변경돼서요!
아니시라면 9.5.0 버전으로 변경 후 pnpm i 해서 다시 push 부탁드립니다 🙂

++) 아래 리뷰에서도 언급하긴 했는데 Label에 기본 스타일로 mt-96이 설정되어있어요 😂 해당 부분 삭제 부탁드려요 ㅎㅎ..

2024-08-14 10:55 UTC, sangminlee98 commented on packages/ui/src/ui/checkbox/CheckBox.tsx
> +export default CheckBox;
label태그 안에 checkbox가 있는 구조인 것 같아요..!
id값을 넘겨주고 checkbox의 id와 label의 htmlFor에 연결시켜주는 방식으로 많이 사용하는 것 같습니다.
(실제 backend로 넘겨줄 값과 label로 보여줄 값을 구분하기 위해)
https://www.radix-ui.com/primitives/docs/components/checkbox#checkbox

label태그도 기존에 만들어둔 Label 디자인 컴포넌트 사용하면 될 것 같아요!
(현재 Label 컴포넌트에 mt-96이 적용되어 있는데 수정하면서 해당 부분도 같이 삭제해주세요 😂)

아래는 제가 에릭님이 만들어두신 컴포넌트 기반으로 살짝 수정해봤어요!
이런 식으로 수정하면 어떨까 싶습니다.
```tsx
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { CheckIcon } from "@radix-ui/react-icons";
import clsx from "clsx";
import { Label } from "../form";

interface CheckBoxProps {
  id: string;
  label?: string;
  labelClassName?: string;
  disabled?: boolean;
  checked?: boolean;
  onCheckedChange?: (checked: boolean) => void;
}

const CheckBox = ({
  id,
  label,
  labelClassName,
  disabled,
  checked,
  onCheckedChange,
}: CheckBoxProps) => (
  <div className={"flex items-center gap-2"}>
    <CheckboxPrimitive.Root
      className={clsx(
        "shrink-0 w-4 h-4 rounded border-2 border-[#D1D5DB] flex items-center justify-center",
        "data-[state=checked]:bg-[#1C2134] data-[state=checked]:border-none data-[state=checked]:text-white",
        "disabled:bg-[#F1F5F9] disabled:cursor-not-allowed disabled:opacity-50"
      )}
      id={id}
      disabled={disabled}
      checked={checked}
      onCheckedChange={onCheckedChange}
    >
      <CheckboxPrimitive.Indicator>
        <CheckIcon />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
    <Label className={labelClassName} htmlFor={id}>
      {label}
    </Label>
  </div>
);

export default CheckBox;

```

2024-08-14 10:55 UTC, sangminlee98 commented on packages/ui/src/ui/radioGroup/RadioGroup.tsx
> +}
이 props는 모두 필수값인가요?
checkbox에서는 optional이어서 어떤게 맞는걸까요??

2024-08-14 10:55 UTC, sangminlee98 commented on packages/ui/src/ui/switch/Switch.tsx
> +export default Switch;
Switch도 Label과 함께 쓰이는 경우도 있을 것 같아서 추가해봤습니다!
https://www.radix-ui.com/primitives/docs/components/switch#switch
shadcd/ui가 radix ui 기반으로 만들어져 있기 때문에 radix의 primitive 컴포넌트 구조를 참고해서 만드시면 좋을 것 같아요!

```tsx
import * as SwitchPrimitive from "@radix-ui/react-switch";
import clsx from "clsx";
import { Label } from "../form";

interface SwitchProps {
  id: string;
  label?: string;
  checked?: boolean;
  labelClassName?: string;
  disabled?: boolean;
  onCheckedChange?: (checked: boolean) => void;
}

const Switch = ({
  id,
  label,
  checked,
  disabled,
  labelClassName,
  onCheckedChange,
}: SwitchProps) => (
  <div className="flex items-center gap-2">
    <Label className={labelClassName} htmlFor={id}>
      {label}
    </Label>
    <SwitchPrimitive.Root
      checked={checked}
      disabled={disabled}
      onCheckedChange={onCheckedChange}
      className={clsx(
        "w-9 h-5 rounded-full relative bg-black/[.2] data-[state=checked]:bg-black outline-none",
        "disabled:cursor-not-allowed disabled:opacity-35"
      )}
      id={id}
    >
      <SwitchPrimitive.Thumb className="block w-4 h-4 bg-white rounded-full transition-transform duration-200 translate-x-0.5 will-change-transform data-[state=checked]:translate-x-[19px]" />
    </SwitchPrimitive.Root>
  </div>
);

export default Switch;

```

2024-08-14 14:00 UTC, sangminlee98 reviewed
리뷰 확인 부탁드립니다 🙇‍♂️
그리고 혹시 pnpm 버전이 9.5.0이 맞을까요?? `pnpm i` 명령어 입력하니 lock파일이 변경돼서요!
아니시라면 9.5.0 버전으로 변경 후 pnpm i 해서 다시 push 부탁드립니다 🙂

++) 아래 리뷰에서도 언급하긴 했는데 Label에 기본 스타일로 mt-96이 설정되어있어요 😂 해당 부분 삭제 부탁드려요 ㅎㅎ..

2024-08-14 14:00 UTC, sangminlee98 commented on packages/ui/src/ui/radioGroup/RadioGroup.tsx
> +);
RadioButton도 Label 컴포넌트 사용하시면 될 것 같아요!
Label과 radio button을 연결하기 위한 id, htmlFor은 prop으로 id를 받아서 사용하셔도 될 것 같고
기존에 받는 value값으로 해도 괜찮을 것 같아요!

```tsx
const RadioButton = ({
  value,
  label,
  disabled,
  labelClassName,
}: RadioButtonProps) => (
  <div className="flex items-center gap-3">
    <RadioGroupPrimitive.Item
      disabled={disabled}
      className="bg-white w-[22px] h-[22px] rounded-full border-2 border-solid  border-[#E5E8EB] disabled:cursor-not-allowed disabled:opacity-60 disabled:bg-[#F1F5F9]"
      value={value}
      id={value}
    >
      <RadioGroupPrimitive.Indicator className="flex items-center justify-center w-full h-full relative after:w-3 after:h-3 after:rounded-full after:bg-black" />
    </RadioGroupPrimitive.Item>
    <Label className={labelClassName} htmlFor={value}>
      {label}
    </Label>
  </div>
);
```

2024-08-15 08:01 UTC, ww8007 requested changes
간단한 코멘트 몇 개 남겼습니다! 만약 내용이 조금 이상하다고 생각 드시면 다시 review 요청 남겨주세요
구현 하느라 고생 많으셨어요 😃

2024-08-15 08:01 UTC, ww8007 commented on packages/ui/src/ui/radioGroup/RadioGroup.stories.tsx
> +];
사소한거긴 한데 각각의 아이템들이 어떤 버튼에 매칭되는 값들인지 변수명에서 드러나도 좋을 것 같아요 👍
ex) `defaultButtonItems`, `disabledItems`, `groupItems`

button이 들어가는게 좋은지 빼는게 좋은지는 장현님이 판단해주시면 될거 같습니다!

2024-08-15 08:01 UTC, ww8007 commented on packages/ui/src/ui/checkbox/CheckBox.tsx
> +  labelClassName?: string;
혹시 `labelClassName`의 경우에는 props에서 제거하고 `className` 자체로 사용하는게 어떨까요?
checkbox의 모든 내부 컴포넌트에 대한 className을 부여하는 방식이 아니라면 다른 컴포넌트와 동일하게
`className`으로 가져가도 무방하지 않을까 생각이 들어서요!
className으로 사용 하더라도 인지상으로도 가장 외곽의 엘리먼트에 대한 제어를 한다는 생각이 들 것 같습니다. 
아니면 터보레포를 쓰니까 구현부를 보러 오지 않을까 생각이 들어요.

아니면 label의 타입을 확장해서 Props에 확장하는 방식도 있을거 같아요.

2024-08-15 08:01 UTC, ww8007 commented on packages/ui/src/ui/switch/Switch.tsx
> +export default Switch;
만약에 label을 추가 한다면 label이 붙는 위치가 디자인 시스템에서 확장되면 좋을거 같아요
현재 구조로서는 label을 오른쪽으로 붙이기 어려워보여서 🥲
근데 저희 Switch를 사용하는 페이지가 없는거 같은데 따로 있나요?

또한 label이 있는지 체크하고 렌더링을 해야할거 같습니다.
```tsx
{!!label.length && (
  <Label className={labelClassName} htmlFor={id}>
        {label}
  </Label>
)}
```

2024-08-15 08:01 UTC, ww8007 commented on packages/ui/src/ui/radioGroup/RadioGroup.tsx
> +  labelClassName: string;
여기도 위와 동일한 의견 입니다!

2024-08-15 08:01 UTC, ww8007 commented on packages/ui/src/ui/checkbox/CheckBox.stories.tsx
> +  tags: ['autodocs'],
autodocs를 이용하는 것도 좋지만 좀 더 사용 용례나 이 컴포넌트의 역할을 명확하게 알려줄 수 있도록
mdx 문서로 만들어보는게 어떨까요?
시작하기 어렵다면 저나 @sangminlee98 가 작성한 예시를 참고해도 좋을 것 같아요!

2024-08-15 08:17 UTC, sangminlee98 commented on packages/ui/src/ui/checkbox/CheckBox.stories.tsx
> +  tags: ['autodocs'],
https://www.notion.so/docs-97995a586bcd4abb88c25e0b0822fa14?pvs=4
간단하게 Docs 작성한 사용법을 태스크보드 문서에 적어놨습니다!
https://storybook.js.org/docs/writing-docs/doc-blocks
공식 문서에서 각 블록에 대한 설명도 잘 나와있어서 참고하시면 좋을 것 같아요 🙂

2024-08-18 09:36 UTC, ww8007 approved these changes
LGTM! 고생하셨습니다. 변수명 소문자만 나중에 수정되면 좋을 것 같아요!

2024-08-18 09:36 UTC, ww8007 commented on packages/ui/src/ui/radioGroup/RadioGroup.stories.tsx
> +];
변수명은 소문자로 시작하면 어떨까요?

2024-08-18 09:37 UTC, ww8007 commented on packages/ui/src/ui/radioGroup/RadioGroup.stories.tsx
> +];
그리고 리뷰 내용 아래 commit 내역 담을 수 있어서 확인할 수 있게 달아줘도 좋을 것 같아요

[example]
https://github.com/Wraffle-Inc/wraffle/pull/12/commits/bf8a980adaedc0a7fb4ecd1dfd2f9bb6acedf60a

2024-08-18 12:42 UTC, sangminlee98 approved these changes
리뷰 반영사항 확인했습니다 👍

2024-08-18 13:09 UTC, eric-hjh commented on packages/ui/src/ui/switch/Switch.tsx
> +export default Switch;
스위치를 사용하는 페이지가 아직 피그마에서 확인되지 않아서, 우선 label 추가유무는 추후에 확정되면 추가하는 방향은 어떤가요?

2024-08-18 13:09 UTC, eric-hjh commented on packages/ui/src/ui/radioGroup/RadioGroup.stories.tsx
> +];
[ae1703f](https://github.com/Wraffle-Inc/wraffle/pull/12/commits/ae1703f9d864ce04b4ed3dc6a0982e52af0d5e08)

이렇게 달면 되는건가요?!

2024-08-22 16:41 UTC, ww8007 approved these changes
LGTM!

2024-08-23 15:52 UTC, merged