feat: Typography tailwind config 설정
Wraffle-Inc/wraffle pull request #14
Opened 2024-08-11 14:58 UTC by Joy0w0

## 📖 개요

## 💻 작업사항

-

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-14 21:00 UTC, sangminlee98 requested changes
리뷰사항 반영해주시면 될 것 같습니다! 👍
수정하시면서 사용하지 않는 변수나 import도 같이 삭제해주세요!

2024-08-14 21:00 UTC, sangminlee98 commented on packages/ui/src/shared/styles/globals.css
> +  }
이 코드는 중복으로 추가된 것 같아요!
pull 받아오시는 과정에서 합쳐진 것 같습니다. 제거해주세요!

2024-08-14 21:00 UTC, sangminlee98 commented on packages/ui/src/shared/styles/globals.css
> +}
이 코드도 중복으로 들어갔습니다! 마찬가지로 제거해주세요 🙂

2024-08-14 21:00 UTC, sangminlee98 commented on packages/ui/src/ui/typography/Typography.stories.tsx
> +});
이 코드는 사용하지 않는 것 같아요!
아마 이전 버전의 storybook에서 사용하는 코드인 것 같은데 제거해주시면 될 것 같습니다!

2024-08-14 21:00 UTC, sangminlee98 commented on packages/ui/src/ui/typography/Typography.stories.tsx
> +);
Story에 이왕이면 타입도 같이 넣어주시면 좋을 것 같아요!
Heading같은 경우에는 컴포넌트를 바로 반환하는 함수이니 StoryFn으로 넣어주시면 될 것 같습니다

```tsx
export const Heading: StoryFn<typeof Typography> = () => (
  <>
    <Typography variant='h1'>Heading 1 (32px, Bold, 140%)</Typography>
    <Typography variant='h2'>Heading 2 (24px, Bold, 140%)</Typography>
    <Typography variant='h3'>Heading 3 (20px, Semi Bold, 140%)</Typography>
    <Typography variant='h4'>Heading 4 (17px, Semi Bold, 140%)</Typography>
    <Typography variant='h5'>Heading 5 (16px, Semi Bold, 140%)</Typography>
    <Typography variant='h6'>Heading 6 (15px, Semi Bold, 140%)</Typography>
  </>
);
```

2024-08-14 21:00 UTC, sangminlee98 commented on packages/ui/src/ui/typography/Typography.tsx
> +Typography.displayName = "Typography";
👍

2024-08-15 07:21 UTC, ww8007 requested changes
간단한 코멘트 몇 개 남겼습니다!
중복 코드 제거랑 주석 제거해주시면 좋을거 같아요 👍

2024-08-15 07:21 UTC, ww8007 commented on packages/ui/src/shared/styles/globals.css
> +  font-style: normal;
webview 형식인걸 고려한다면 좀 더 다양한 확장자(`woff`, `woff2`, `otf`) 등을 추가하여
사이즈에 대한 이점을 가져가 보는건 어떨까요?

2024-08-15 07:21 UTC, ww8007 commented on packages/ui/src/ui/typography/Typography.tsx
> +    // const Comp = asChild ? Slot : "div";
주석은 삭제해도 좋을 것 같아요!

2024-08-15 07:35 UTC, ww8007 requested changes
간단한 코멘트 몇 개 남겼습니다! 만약 내용이 조금 이상하다고 생각 드시면 다시 review 요청 남겨주세요
구현 하느라 고생 많으셨어요 😃

2024-08-18 10:13 UTC, eric-hjh commented on packages/shared/tailwind-config/tailwind.config.ts
> +      },
```
fontSize: {
  'heading-1': [
          '2rem',
          {
            lineHeight: '1.4',
            fontWeight: '700',
          },
        ],
}
```
이렇게 한번에 heading-1 속성을 부여할 수 있게 설정하는건 어떨까요??
[[fontSize, { lineHeight?, letterSpacing?, fontWeight? }]](https://tailwindcss.com/docs/font-size#providing-a-default-line-height) 순으로 설정할 수 있습니다!

2024-08-18 10:19 UTC, eric-hjh commented on packages/shared/tailwind-config/tailwind.config.ts
> +      },
기존 tailwind 에서 font  weight 로 medium = 500, semibold = 600, bold = 700으로 설정되어있어서, 커스텀 설정을 해주지 않아도 된다 생각하는데, 어떻게 생각하시나요?

2024-08-19 21:14 UTC, Joy0w0 commented on packages/shared/tailwind-config/tailwind.config.ts
> +      },
```
fontSize: {
        h1: [
          "32px",
          {
            lineHeight: "1.4",
            fontWeight: "700",
          },
        ],
```
말씀해주신 내용대로 위처럼 바꾸면서 font weight 로 medium = 500, semibold = 600, bold = 700, lint height는 tight = 1.4 로 그대로 적용되기에 장현님께서 덧붙여주신것처럼 fontweight 및 lineheight는 커스텀하지않게 리팩토링 진행했습니다!
피드백 감사합니다!

2024-08-20 10:57 UTC, sangminlee98 approved these changes

2024-08-22 16:41 UTC, ww8007 approved these changes
LGTM!

2024-08-23 05:26 UTC, merged