feat: roundButton, Tag, Tooltip 컴포넌트 생성
Wraffle-Inc/wraffle pull request #16
Opened 2024-08-14 12:29 UTC by Ajeong-Im

## 📖 개요

## 💻 작업사항

- roundButton 컴포넌트 생성
- Tag 컴포넌트 생성
- Tooltip 컴포넌트 생성

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-14 21:03 UTC, sangminlee98 requested changes
👍

2024-08-14 21:03 UTC, sangminlee98 commented on packages/ui/src/ui/tooltip/CustomTooltip.tsx
> +import * as React from "react";
해당 파일 이름이 `CustomTooltip.tsx`인데 혹시 `PrimitiveTooltip.tsx`로 변경 가능할까요?
저도 Select 컴포넌트 만들면서 사용한 radix ui의 primitive 컴포넌트는 네이밍 컨벤션으로 Primitive를 붙혀서 만들어서 통일시키면 좋을 것 같습니다!

2024-08-15 07:35 UTC, ww8007 requested changes
간단한 코멘트 몇 개 남겼습니다! 만약 내용이 조금 이상하다고 생각 드시면 다시 review 요청 남겨주세요
구현 하느라 고생 많으셨어요 😃

2024-08-15 07:35 UTC, ww8007 commented on packages/ui/src/ui/roundButton/RoundButton.stories.tsx
> +};
기본적인 사용 용례를 보여주는 컴포넌트니까
`Button` 보다는 `Appearance`의 네이밍이 좋을 것 같은데 어떠신가요?

2024-08-15 07:35 UTC, ww8007 commented on packages/ui/src/ui/roundButton/RoundButton.tsx
> +        false: "bg-[#F4F4F5] text-[#52525B]", // 비선택된 상태
`selected : true, false`가 너무 명확하게 상태를 드러내고 있어서
요 정도 주석은 생략해도 괜찮지 않을까? 생각 합니다.

2024-08-15 07:35 UTC, ww8007 commented on packages/ui/src/ui/roundButton/RoundButton.stories.tsx
> +  tags: ["autodocs"],
`autodocs`를 이용하는 것도 좋지만 좀 더 사용 용례나 이 컴포넌트의 역할을 명확하게 알려줄 수 있도록
`mdx` 문서로 만들어보는게 어떨까요?
시작하기 어렵다면 저나 @sangminlee98 가 작성한 예시를 참고해도 좋을 것 같아요!

2024-08-15 07:35 UTC, ww8007 commented on packages/ui/src/ui/tag/Tag.stories.tsx
> +  tags: ["autodocs"],
여기도 위의 내용과 동일 합니다!

2024-08-15 07:35 UTC, ww8007 commented on packages/ui/src/ui/tooltip/Tooltip.tsx
> +        </TooltipContent>
혹시 radix의 예시에서는 `Portal` 형식으로 `Content`를 렌더링 하던데
기존 돔 트리에 대한 영향이 없도록 `Portal`을 사용하는게 어떨까요?

```tsx
const TooltipDemo = () => {
  return (
    <Tooltip.Provider>
      <Tooltip.Root>
        <Tooltip.Trigger asChild>
          <button className="IconButton">
            <PlusIcon />
          </button>
        </Tooltip.Trigger>
        <Tooltip.Portal>
          <Tooltip.Content className="TooltipContent" sideOffset={5}>
            Add to library
            <Tooltip.Arrow className="TooltipArrow" />
          </Tooltip.Content>
        </Tooltip.Portal>
      </Tooltip.Root>
    </Tooltip.Provider>
  );
};
```

https://www.radix-ui.com/primitives/docs/components/tooltip

2024-08-15 08:02 UTC, ww8007 requested changes
간단한 코멘트 몇 개 남겼습니다! 만약 내용이 조금 이상하다고 생각 드시면 다시 review 요청 남겨주세요
구현 하느라 고생 많으셨어요 😃

2024-08-15 08:21 UTC, sangminlee98 commented on packages/ui/src/ui/roundButton/RoundButton.stories.tsx
> +  tags: ["autodocs"],
https://www.notion.so/docs-97995a586bcd4abb88c25e0b0822fa14?pvs=4
간단하게 Docs 작성한 사용법을 태스크보드 문서에 적어놨습니다!
https://storybook.js.org/docs/writing-docs/doc-blocks
공식 문서에서 각 블록에 대한 설명도 잘 나와있어서 참고하시면 좋을 것 같아요 🙂

2024-08-15 09:19 UTC, sangminlee98 commented on packages/ui/src/ui/roundButton/RoundButton.tsx
> +import * as React from "react";
해당 컴포넌트 이름을 RoundButton이 아닌 다른 이름으로 하기로 했던 것 같은데..
@ww8007 혹시 기억나시나요??

2024-08-15 17:13 UTC, sangminlee98 commented on packages/ui/src/ui/roundButton/RoundButton.tsx
> +import * as React from "react";
ChipButton이나 PillButton이 좋을 것 같아요.

2024-08-18 16:51 UTC, Ajeong-Im commented on packages/ui/src/ui/tooltip/CustomTooltip.tsx
> +import * as React from "react";
변경 완료했습니다!!🙆‍♀️

2024-08-18 16:52 UTC, Ajeong-Im commented on packages/ui/src/ui/roundButton/RoundButton.stories.tsx
> +};
apperance에 맞게 종류별로 보여주도록 변경했습니다!

2024-08-18 16:52 UTC, Ajeong-Im commented on packages/ui/src/ui/roundButton/RoundButton.stories.tsx
> +  tags: ["autodocs"],
autodocs에서 mdx 문서 작성으로 변경했습니다!

2024-08-18 16:53 UTC, Ajeong-Im commented on packages/ui/src/ui/roundButton/RoundButton.tsx
> +import * as React from "react";
ChipButton으로 변경했습니다!!🙆‍♀️

2024-08-20 10:57 UTC, sangminlee98 approved these changes

2024-08-25 07:10 UTC, ww8007 approved these changes
LGTM!

2024-08-25 07:12 UTC, merged