feat: 로그인 api 구현
Wraffle-Inc/wraffle pull request #17
Opened 2024-08-16 17:09 UTC by HyunTaek5

## 📖 개요
- 로그인 api 구현

## 💻 작업사항

- 액세스/리프레시 토큰 기반 인증/인가 처리
- 토큰 만료 관련 예외처리 추가
- redis에 ```auth:{userId}``` 키로 accessToken 및 refreshToken 값 저장

## 💡 작성한 이슈 외에 작업한 사항

- 없습니다.

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-08-16 17:47 UTC, baekhangyeol requested changes
고생하셨습니다! 🙇‍♂️
몇 가지 궁금한 사항 남겨놨습니다!

2024-08-16 17:47 UTC, baekhangyeol commented on apps/back/apps/application/auth/service/auth.service.ts
>    }
이 부분에서 로그인한 다음에, sign_in_history 테이블에 기록을 저장한다고 했던 것 같은데 그 부분은 추후 구현 예정이신건가요?!

2024-08-16 17:47 UTC, baekhangyeol commented on apps/back/apps/application/auth/service/auth.service.ts
>    }
추가로, 제 로컬 환경에서는 로그인 한 후에 redis에 값이 저장되지 않는 것 같습니다 ㅠㅠ

2024-08-16 19:17 UTC, HyunTaek5 commented on apps/back/apps/application/auth/service/auth.service.ts
>    }
sign_in_history 테이블 기록 저장은 추후 구현 예정 _(레포 분리 이후)_ 예정이에요!

redis 저장 이슈는 기존에 사용하던 **redis-store 라이브러리가 memory에 KV 데이터를 저장하는 이슈**가 있어서 **ioredis** 기반으로 전부 전환해두었습니다 😁

2024-08-16 19:19 UTC, baekhangyeol commented on apps/back/apps/application/auth/service/auth.service.ts
>    }
<img width="969" alt="image" src="https://github.com/user-attachments/assets/bcd665fd-99c6-4262-81b8-e8606ac83c42">
확인했습니다!🙇‍♂️

2024-08-16 19:20 UTC, baekhangyeol approved these changes
🙇‍♂️

2024-08-23 16:27 UTC, HyunTaek5 commented
https://github.com/Wraffle-Inc/wraffle-api

해당 레포로 코드 이관에 따라 PR close 하겠습니다

2024-08-23 16:27 UTC, closed without merging