feat: 이벤트 도메인 API 구현
Wraffle-Inc/wraffle pull request #18
Opened 2024-08-17 02:00 UTC by baekhangyeol

## 📖 개요
- 이벤트 생성 API 구현
- 이벤트 수정 API 구현
- 이벤트 개별 조회 API 구현

## 💻 작업사항
- Interceptor를 통해 이벤트 개별 조회 API가 호출 될 때 조회수 1 증가하도록 구현
- 이벤트를 생성할 때, 해당하는 images를 테이블에 삽입
- 상품에 대한 이미지의 구별을 위해 `raffle.enum.ts` 에 PRODUCT 추가
- 응모하기 API의 호출을 위해 이벤트 개별 조회 시 type(RAFFLE or EVENT)도 함께 전달

- API의 테스트를 위해 임시로 `@Public` 사용, 추후 #17 머지 후 User에 대한 처리해줄 예정

## 💡 작성한 이슈 외에 작업한 사항
- 없습니다

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-08-17 13:54 UTC, HyunTaek5 requested changes
이벤트 도메인 API 작업하시느라 고생많으셨어용! 👍 

코드 살펴보다 이것저것 많이 코멘트를 달아두었는데 한번 확인해주시고 수정 반영해주시면 좋을거 같습니다 🙇

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/dto/request/create-event.dto.ts
> +  @IsNotEmpty()
저희 DTO단에 `@IsNotEmpty` 안붙여도 자동으로 empty validation 걸려서 옵셔널한 값들만 `@IsOptional` 추가해주시면 됩니당

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/event.module.ts
> +  controllers: [EventController],
이미 EventController를 app.module에 추가해둬서 EventModule에는 따로 명시할 필요가 없을거 같습니다!

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/dto/response/get-event.dto.ts
> +  @IsInt()
리턴 DTO의 경우에는 DB에서 넘어온 엔티티를 DTO에 매핑하는 형태라 타입 validation이 필요없고 `@ApiProperty`랑 `@Exclude(), @Expose`만 세팅해주시면 될거 같습니다!

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/service/event.service.ts
> +      return new CustomResponse<GetEventDto>(404, "E001", null);
여기서 CustomResponse로 excpetion을 리턴하게되면 HTTP 응답코드는 200인데 내부 body의 status 상태값만 404로 응답하게될거라 `throw new ResourceNotFoundException('응답하려는 메세지','응답코드')` 처럼 해주시면 됩니다!

infrastructure/error/index.ts에 들어가보시면 401,403, 404등 몇 가지 상황에 대해 미리 생성해둔 exception들이 있습니다 😃

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/service/event.service.ts
> +  ): Promise<IResponse<any>> {
any 보다는 응답값을 명시해주는게 좋을거 같아요! 😃

2024-08-17 13:54 UTC, HyunTaek5 commented on apps/back/apps/application/event/service/event.service.ts
> +  async increaseViewCount(id: number): Promise<void> {
increament 메소드를 사용해서 잘 구현해주셨는데 현재 구현한 방식은 **이벤트 1번 조회마다 DB에 DML이 매번 발생하게되어** 부하가 걸릴 가능성이 있어보여요! 추후 redis에 요청 ip와 클릭된 id를 키로 저장해두고 스케쥴링으로 한번에 DB 업데이트 시키는 방식으로 전환하면 될거 같습니다 😃 

DML이 매번 발생하는데 부하가 걸릴 가능성의 이유: 해당 로직은 viewCount를 1씩 increment하는데 해당 메소드는 update 쿼리를 사용해서 업데이트하는 row에 쓰기(Exclusive)락을 잡게되요! 그런데 조회가 빈번하게 발생하는 row에 대해 쓰기락이 잡히게되면 조회가 불가능한 상태가 빈번하게 발생해서 추후 데드락 상태가 발생할 수 있어요!

2024-08-17 13:57 UTC, baekhangyeol commented on apps/back/apps/application/event/dto/request/create-event.dto.ts
> +  @IsNotEmpty()
확인했습니다!

2024-08-17 14:03 UTC, baekhangyeol commented on apps/back/apps/application/event/dto/response/get-event.dto.ts
> +  @IsInt()
다른거 다 빼놨었는데 2개만 validation을 적어놨었네요 😅

2024-08-17 14:14 UTC, baekhangyeol commented on apps/back/apps/application/event/service/event.service.ts
> +  async increaseViewCount(id: number): Promise<void> {
넵! TODO로 달아두도록 하겠습니다!
좋은 정보 감사합니다! 😊

2024-08-17 14:16 UTC, baekhangyeol commented on apps/back/apps/application/event/service/event.service.ts
> +  async increaseViewCount(id: number): Promise<void> {
구현은 추후에 User 붙히면서 같이 진행하겠습니다

2024-08-17 14:34 UTC, HyunTaek5 approved these changes
수정사항 전부 확인했습니다! 고생하셨습니다! 👍

2024-08-22 18:08 UTC, kubit2 commented
**LGTM ✨**
고생하셨습니다 !!

2024-08-22 18:40 UTC, merged