[WRDS-12] BottomNavigation 컴포넌트 및 모든 아이콘 추가
Wraffle-Inc/wraffle pull request #19
Opened 2024-08-18 12:10 UTC by gyeong3un2

## 📖 개요
BottomNavigation 컴포넌트 및 모든 아이콘 추가

## 💻 작업사항

- BottomNavigation 컴포넌트 추가
- 프로젝트에 필요한 모든 아이콘 SVG를 `SVG 스프라이트 기법`을 사용하여 추가

## 💡 작성한 이슈 외에 작업한 사항

-

## 🤔 이슈 사항

- `plus` 아이콘과 `credit card` 아이콘만 나타나지 않는 이슈가 발생
  -> 여러 다른 아이콘으로도 시도했지만 적용되지 않아서, PR 올린 후에도 계속해서 시도해볼 예정

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-08-18 13:58 UTC, sangminlee98 requested changes

2024-08-18 13:58 UTC, sangminlee98 commented on packages/ui/src/ui/iconWithLabel/IconWithLabel.tsx
> +}
{Icon}자리에 SVGIcon 컴포넌트가 들어가는데 SVGIcon 컴포넌트가 position: absolute 속성이 붙어있다보니 아래와 같이 보이네요 😂
확인 후 수정 부탁드리겠습니다!

![스크린샷 2024-08-18 오후 10 58 22](https://github.com/user-attachments/assets/8d06bb56-981a-41a2-a1a2-8fd95653b4de)

2024-08-19 11:44 UTC, gyeong3un2 commented on packages/ui/src/ui/iconWithLabel/IconWithLabel.tsx
> +}
오 그 부분을 놓쳤네요! 찾아주셔서 감사합니다! 🙌

[이슈 관련 수정 링크](https://github.com/Wraffle-Inc/wraffle/pull/19/commits/c828ded48cb9ccf132c2dd0b96634f4558e3c643)

2024-08-20 11:17 UTC, sangminlee98 requested changes

2024-08-20 11:17 UTC, sangminlee98 commented on packages/ui/src/ui/bottomNavigation/BottomNavigation.tsx
> +            Icon={<SVGIcon id={id} withLabel />}
BottomNavigation에서 `IconWithLabel` 컴포넌트에 Icon을 withLabel로 전달하면
Icon이 absolute가 되므로 label과 아이콘이 겹쳐서 보이는 것 같아요!
현재 BottomNavigation을 확인해보면 여전히 겹쳐있습니다 😂

2024-08-22 11:41 UTC, gyeong3un2 commented on packages/ui/src/ui/bottomNavigation/BottomNavigation.tsx
> +            Icon={<SVGIcon id={id} withLabel />}
아 제가 변수명을 잘못지어서 헷갈렸나보네요ㅠ

`withBadge`로 수정해서 Badge가 있을 경우 `absolute`가 되도록 수정했습니다!
체크해주셔서 감사합니다!

관련 커밋 기록: https://github.com/Wraffle-Inc/wraffle/pull/19/commits/5aaf16c408705742a60447b7d5295289ef6aa86f, https://github.com/Wraffle-Inc/wraffle/pull/19/commits/9a76538643d376086434e21ec7f3872102613cae

2024-08-22 16:57 UTC, sangminlee98 commented on packages/ui/src/ui/bottomNavigation/BottomNavigation.tsx
> +            Icon={<SVGIcon id={id} withLabel />}
확인했습니다! 수정 감사합니다 🙇‍♂️

2024-08-22 16:57 UTC, sangminlee98 approved these changes
LGTM 👍

2024-08-25 13:50 UTC, merged