feat: 카드 도메인 API 구현
Wraffle-Inc/wraffle pull request #20
Opened 2024-08-18 13:42 UTC by kubit2

## 📖 개요

- 카드 등록 API 구현
- 카드 조회 API 구현
- 카드 삭제 API 구현
- 주사용 카드 변경 API 구현

## 💻 작업사항
- 카드 조회 시, 각 카드 정보는 마스킹 처리되도록 구현
- CardDetailDto는 개별 카드의 상세 정보를 나타내고, GetCardDto는 여러 개의 CardDetailDto를 배열 형태로 감싸 전체 카드 목록을 관리하고, API 응답 형식을 정의하는 데 사용
- API의 테스트를 위해 임시로 `@Public 사용`, 추후 #17 머지 후 User에 대한 처리해줄 예정

## 💡 작성한 이슈 외에 작업한 사항

- 없습니다

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-08-18 16:10 UTC, HyunTaek5 requested changes
구현하느라 고생많으셨어요! 👍  사소한 코멘트 몇개 달아두었는데 확인해주시면 좋을거 같습니다 😄

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/application/card/card.module.ts
> +  controllers: [CardController],
CardController를 app.module에 명시해주셔서 card.module에는 추가적으로 명시를 안해주셔도 될거 같아요! 😃

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/application/card/dto/response/get-card.dto.ts
> +  @IsInt()
아마도 다른 DTO에서 복붙하시다가 깜빡 남기신거 같지만? class-validator는 response dto에서는 사용하지 않으셔도 되요! 😄

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/application/card/dto/response/get-card.dto.ts
> +  @ApiProperty({ type: [CardDetailDto], description: "카드 목록" })
class-transformer의 `@Type`으로 추가적으로 쓰는 것도 좋을거 같아요!

`@Type(() => CardDetailDto)`

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/domain/card/card.entity.ts
>    @Column({ comment: "주사용 카드 여부" })
칼럼 옵션중에 default 옵션이 있어요! 칼럼에 옵션으로 추가해두는 것도 좋을 거 같네요 😃

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/application/card/service/card.service.ts
> +
없는 카드 id에 대한 요청이 들어왔을때 예외처리가 필요할거 같아요!

2024-08-18 16:10 UTC, HyunTaek5 commented on apps/back/apps/front-api/src/card/card.controller.ts
> +  async deleteCard(@Param("id") id: number): Promise<IResponse<null>> {
`@Param`을 쓸때 기본으로 id가 number로 형변환이 안될거라 ParseIntPipe를 Param 데코레이터안에 붙여주시는게 좋아요! 😃 

`@Param('id', ParseIntPipe)` 처럼 작성해주시면 될거에요!

2024-08-18 16:42 UTC, baekhangyeol reviewed
모든 API 잘 동작하네요! 고생하셨습니다🙇‍♂️
궁금한 사항이 몇 가지 있어서 코멘트 남깁니다!

1. 주사용 카드 변경 API를 사용할 때 하나의 카드의 isDefault를 바꿀 수 있도록 되어있는데, 다른 카드가 이미 true라면 API를 호출해도 그 카드가 계속 true로 남아있더라구요! 2개의 카드가 true인 경우에는 어떻게 처리되는건가요??

2024-08-20 18:00 UTC, SimoKii commented
> 모든 API 잘 동작하네요! 고생하셨습니다🙇‍♂️ 현택님이 달아주신 부분만 수정해주시면 될 것 같아요👍 궁금한 사항이 한 가지 있어서 코멘트 남깁니다!
> 
> 주사용 카드 변경 API를 사용할 때 하나의 카드의 isDefault를 바꿀 수 있도록 되어있는데, 다른 카드가 이미 true라면 API를 호출해도 그 카드가 계속 true로 남아있더라구요! 2개의 카드가 true인 경우에는 어떻게 처리되는건가요??

해당 로직이 구현되지 않은 것 같습니다!
주사용 카드를 변경했을 때, 이전 주사용 카드에 대해 false 처리를 하도록 하겠습니다 :) 😊

2024-08-20 18:17 UTC, kubit2 commented on apps/back/apps/domain/card/card.entity.ts
>    @Column({ comment: "주사용 카드 여부" })
isDefault 칼럼에 대해서만 false 값을 default로 설정하면 될까요?
아니면, billingKey 칼럼에 대해서도 빌링키 값이 제공되지 않을 때 기본 값을 자동으로 할당하는 방식을 말씀하시는 걸까요?
다른 칼럼에 대한 default 값은 어떻게 설정해야하는건지 궁금합니다!

2024-08-20 18:20 UTC, HyunTaek5 commented on apps/back/apps/domain/card/card.entity.ts
>    @Column({ comment: "주사용 카드 여부" })
isDefault에 대해서만 default값을 false로 설정하면 될거 같습니다! 다른 칼럼들의 경우 프론트에서 넘어오는 값들을 서비스레이어에서 지정하면 될거 같습니다 😄

2024-08-20 19:05 UTC, HyunTaek5 approved these changes
작업하시느라 고생하셨습니다! 👍 
**LGTM** 🙌

2024-08-20 19:19 UTC, baekhangyeol approved these changes
🙇‍♂️

2024-08-20 19:19 UTC, merged