feat: Raffle Card 컴포넌트 추가
Wraffle-Inc/wraffle pull request #21
Opened 2024-08-18 15:59 UTC by sangminlee98

## 📖 개요
래플 카드 디자인 컴포넌트 추가 작업중

## 💻 작업사항

- RaffleCard 컴포넌트 생성
- RaffleCard Story 생성 

## 🤔 고려사항

- Typo 컴포넌트, SVGIcon 컴포넌트, Hashtag 컴포넌트 필요
- 제목 길어질 경우 Ellipsis 처리
- 해시태그 많아질 경우 어떻게 처리할 지 UX 측면에서 고려

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-22 12:06 UTC, gyeong3un2 requested changes
간단한 코멘트 몇 개 남겼습니다!
구현하시느라 고생하셨습니다! 👍

2024-08-22 12:06 UTC, gyeong3un2 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +    <div className="w-[160px] h-[267px">
height의 대괄호 닫기가 빠진 것 같습니다!

2024-08-22 12:06 UTC, gyeong3un2 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +  return (
return 문 앞에 줄바꿈하는 거를 프로젝트 코드 컨벤션으로 하는 건 어떤가요??

저희 회사에서도 코드 가독성 향상을 위해 return 문 앞에 줄바꿈하고 있어서 말씀드립니다!

2024-08-22 16:53 UTC, sangminlee98 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +    <div className="w-[160px] h-[267px">
오! 전혀 모르고 있었어요 😂 꼼꼼하게 확인해주셔서 감사합니다!

[72077b6](https://github.com/Wraffle-Inc/wraffle/pull/21/commits/72077b61575e5d918edd583a87da9362fc2a8d82)

2024-08-22 16:55 UTC, sangminlee98 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +  return (
JSX return 부분을  줄바꿈으로 구분하니까 확실히 가독성이 좋아질 것 같네요!
다음 회의때 컨벤션으로 논의 한번 해봅시다 🙂

[64de80b](https://github.com/Wraffle-Inc/wraffle/pull/21/commits/64de80b7f2f8b5b529f9340fa6207a5c09eb039a)

2024-08-25 13:52 UTC, gyeong3un2 approved these changes
LGTM 👍

2024-08-25 14:39 UTC, merged