feat: Calendar 컴포넌트 추가
Wraffle-Inc/wraffle pull request #22
Opened 2024-08-18 22:52 UTC by eric-hjh

## 📖 개요

## 💻 작업사항

- Calendar컴포넌트 추가

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-29 17:33 UTC, sangminlee98 requested changes
리뷰 확인해주세요!

2024-08-29 17:33 UTC, sangminlee98 commented on packages/ui/src/ui/calendar/Calendar.stories.tsx
> +};
CalendarForRender 함수를 따로 만들어서 selected와 setSelected에 대한 prop으로 기본으로 넣고 계신 것 같아요!
args가 any타입으로 들어가는데 직접 사용하는 것이 아니긴 하지만 타입이 지정되면 좋을 것 같습니다
아래 코드처럼 state가 prop으로 전달되는 기본 Template을 만들고 해당 Template을 사용하는 방식으로 적용해보시면 될 것 같아요!

```tsx
import type { Meta, StoryFn } from "@storybook/react";
import CalendarForm from "./Calendar";
import { useState } from "react";

const meta = {
  title: "Components/Calendar",
  component: CalendarForm,
} satisfies Meta<typeof CalendarForm>;

export default meta;

const Template: StoryFn<typeof CalendarForm> = (args) => {
  const [selected, setSelected] = useState<Date | undefined>();
  return (
    <CalendarForm {...args} selected={selected} setSelected={setSelected} />
  );
};

export const CalendarFormDefault = Template.bind({});
CalendarFormDefault.args = {
  formLabel: "어떤 일정을 정할지에 대해 작성하는 라벨입니다.",
  className: "",
  dateLabel: "선택한 날짜가 표시되기 전 보여지는 라벨입니다",
};

```

2024-08-29 17:33 UTC, sangminlee98 commented on packages/ui/src/ui/calendar/Calendar.tsx
> +import { DayPicker } from 'react-day-picker';
해당 Calendar 컴포넌트를 src/ui의 index.ts 파일에도 export 해주세요! (Barrel exports)

`export * from "./calendar/Calendar";`

2024-09-01 13:21 UTC, eric-hjh commented on packages/ui/src/ui/calendar/Calendar.stories.tsx
> +};
[수정](https://github.com/Wraffle-Inc/wraffle/pull/22/commits/28e826ec0033b2c990697f8135587505b5b46122) 커밋 입니다!

2024-09-01 19:19 UTC, eric-hjh commented on packages/ui/src/ui/calendar/Calendar.stories.tsx
> +};
추가 [수정사항](https://github.com/Wraffle-Inc/wraffle/pull/22/commits/444c737be5aa86052d6b84d7b38206fb1abf3669) 커밋입니다!

2024-09-04 09:15 UTC, sangminlee98 approved these changes
LGTM 👍

2024-09-05 02:20 UTC, merged