chore: prettier 전역 turbo 명령어등록
Wraffle-Inc/wraffle pull request #23
Opened 2024-08-20 17:39 UTC by Ajeong-Im

## 📖 개요
- prettier 전역 turbo 명령어등록

## 💻 작업사항

- [ ] prettier-config 파일에서 tab-width, jsxSingleQuote 설정
- [ ] 전역으로 프리티어 등록
- [ ] 루트 디렉토리의 turbo.json에 format 명령어 등록

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-22 16:47 UTC, ww8007 approved these changes
좋네요 👍

2024-08-22 17:05 UTC, sangminlee98 requested changes
리뷰 반영 부탁드립니다!

2024-08-22 17:05 UTC, sangminlee98 commented on apps/admin/.eslintcache
> +[{"/Users/im-ajeong/Desktop/wraffle/apps/admin/app/layout.tsx":"1","/Users/im-ajeong/Desktop/wraffle/apps/admin/app/page.tsx":"2","/Users/im-ajeong/Desktop/wraffle/apps/admin/next-env.d.ts":"3","/Use
format 명령어 실행 시 lint에 cache옵션이 포함되어 있기 때문에 `.eslintcache` 파일이 생기는 듯 합니다.
해당 파일은 `.gitignore`에 포함해서 원격 저장소에는 안올리도록 하는게 좋을 것 같아요!

2024-08-22 17:05 UTC, sangminlee98 commented on apps/front/wraffle-webview/.eslintcache
> +[{"/Users/im-ajeong/Desktop/wraffle/apps/front/wraffle-webview/app/layout.tsx":"1","/Users/im-ajeong/Desktop/wraffle/apps/front/wraffle-webview/app/page.tsx":"2","/Users/im-ajeong/Desktop/wraffle/app
위와 동일한 리뷰입니다.

2024-08-22 17:05 UTC, sangminlee98 commented on packages/ui/.eslintcache
> +[{"/Users/im-ajeong/Desktop/wraffle/packages/ui/src/index.tsx":"1","/Users/im-ajeong/Desktop/wraffle/packages/ui/src/shared/index.ts":"2","/Users/im-ajeong/Desktop/wraffle/packages/ui/src/shared/util
위와 동일한 리뷰입니다.

2024-08-23 04:32 UTC, Ajeong-Im commented on apps/admin/.eslintcache
> +[{"/Users/im-ajeong/Desktop/wraffle/apps/admin/app/layout.tsx":"1","/Users/im-ajeong/Desktop/wraffle/apps/admin/app/page.tsx":"2","/Users/im-ajeong/Desktop/wraffle/apps/admin/next-env.d.ts":"3","/Use
수정 완료했습니다!
[7387917](https://github.com/Wraffle-Inc/wraffle/pull/23/commits/7387917d84c318cd7bd0e1969176b1bf4c777a59)

2024-08-25 07:16 UTC, ww8007 approved these changes
👍

2024-08-25 12:32 UTC, sangminlee98 approved these changes

2024-08-28 14:23 UTC, merged