feat: 래플/이벤트 상세 페이지
Wraffle-Inc/wraffle pull request #28
Opened 2024-08-30 20:32 UTC by Ajeong-Im

## 📖 개요

## 💻 작업사항

-

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-09-04 08:28 UTC, eric-hjh commented
브랜치 이름이 짧아요 ^,,^

2024-09-04 08:52 UTC, eric-hjh reviewed
확인부탁드립니다!

2024-09-04 08:52 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +export default function RootLayout({children}: LayoutProps) {
RootLayout이 아닌데 RootLayout입니다

2024-09-09 08:59 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +export default function RootLayout({children}: LayoutProps) {
헉 수정했습니다!!!!

2024-10-22 07:49 UTC, gyeong3un2 reviewed
LGTM! 👍

궁금한 사항 몇 개 코멘트로 남겨뒀습니다!
이건 제 개인적인 견해라서 조금 이상하거나 이해가 안 가신다 생각드시면, 다시 review 요청 남겨주세요!

고생하셨습니다! 😁

2024-10-22 07:49 UTC, gyeong3un2 commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +      ? ['상품', '응모 기간', '당첨자 발표', '추첨 상품', '유의사항']
이 배열과 아래 배열을 상수로 분리하여 관리하면 어떨까요?

분리해서 사용하면 이 배열이 어느 타입인지도 코드보고 바로 알 수 있을 것 같아요!
`type`이 `event`일 경우에는 이 배열이겠구나 라고 할 수 있을 것 같은데, 아래 배열 같은 경우는 어느 타입의 배열인지 모를 수도 있을 것 같아요!

2024-10-22 07:49 UTC, gyeong3un2 commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +    if (type === 'raffle') {
같은 setState를 바라보고 있다면 데이터만 묶어서 사용할 수도 있을 것 같아요!

예를 들면, 
```
const data = {
  raffle: sampleRaffleData,
  event: sampleEventData,
}

if (data[type]) {
  setProductData(data[type]);
} else {
  router.push('/404');
}
```

2024-10-22 07:49 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/features/participate/ParticipateButton.tsx
> +  applyStatus: boolean;
이 변수는 응모 완료 여부여서, true일 때 응모 완료 상태, false일 때 응모 안한 상태인 것 같아요!

그런데 `applyStatus`는 'applied'나 'notApply'와 같이 string 형태로 나누어져 표현되어야 될 것 같은 느낌이 들어요!

그래서 `isApplied` 와 같이 boolean 값을 명확하게 표현하면, 코드 의도가 조금 더 쉽게 이해할 수 있을 것 같아요!

2024-10-22 09:19 UTC, eric-hjh requested changes
궁금한점 몇가지 적어보았습니다!

2024-10-22 09:19 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +}
layout 사용하신 이유가 있을까요?

2024-10-22 09:19 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
따로 훅으로 분리하신 이유가 궁금합니다!

2024-10-22 09:19 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogDescription>
해당부분에서 p태그 안에 p태그랑 div태그를 사용하여 
`This will cause a hydration error.`
하이드레이션 오류가 나타는거 같습니다.

2024-10-22 09:19 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogClose>
위와 동일한 오류입니다. 
asChild를 사용하면 의도대로 될것 같습니다!

2024-10-22 09:19 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogDescription>
모달 사용하신 부분에 공통적으로 해당되는것 같습니다! 그리고  dialog trigger를 사용하지 않으신 이유가 궁금합니다!

2024-10-23 14:30 UTC, ww8007 requested changes
궁금한 점 코멘트 남겼습니다! 작업하실 때 컨벤션에 조금만 더 신경을 써주시면 감사하겠습니다 👍

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +}> = ({productData, sectionRef}) => {
FC를 사용하신 특별한 이유가 있나요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-image-list/ProductImageList.tsx
> +export default ProductImageList;
왜 어떤 파일은 default고 어떤 파일은 export 인가요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/shared/ui/divider/Divider.tsx
> +import React from 'react';
이 import React 문은 꼭 필요한가요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/shared/ui/divider/Divider.tsx
> +export {Divider};
이건 export const Divider가 아닌 이유가 있나요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/share-product-link/ShareModal.tsx
> +                  src='https://i.ibb.co/MDMTKFq/insta.png'
상수로 관리하면 좀 더 보기 편할거 같고
근데 Next의 Image 컴포넌트를 사용하지 않은 이유가 따로 있을까요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
22

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +  }, [isOpen]);
혹시 요건 어떤 이유로 필요한 코드인가요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogDescription>
요번에 use-dialog customHook을 사용하지 않은 이유가 있나요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +      const headerOffset = 115;
115는 무슨 값 인가요?
상수로 분리해도 좋을 것 같아요!

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +  }, [selectedMenu]);
이런 방식 보다는 메뉴를 클릭할 때 함수로 분리해서 가져가면
로직을 이해하기 좀 더 쉬울거 같은데 어떠신가요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/tsconfig.json
> +    "strictNullChecks": true
오 이 부분 빠져있었네요 추가해주셔서 감사합니다!

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoMenu.tsx
> +      style={{scrollbarWidth: 'none'}}
혹시 className과 style이 공존하는 이유가 따로 있나요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +};
왜 이 친구는 interface가 아닌가요?

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/shared/util/formatDate.ts
> +};
![image](https://github.com/user-attachments/assets/8332fc4a-e9d4-4f9e-a5d1-4cda1dc4de71)

이와 같이 다양한 format으로 date가 변환될 수 있음을 고려해서
좀 더 확장성 있는 유틸 함수가 되어도 좋을 것 같아요!
현재 이 formatDate는 하나의 format에만 사용할 수 있는거 같아서
dayjs 같은 라이브러리 사용도 괜찮아보여요!

2024-10-23 14:30 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +// 이미지, 타이틀, 가격
혹시 이건 어떤 정보를 위한 주석 인가요?
타입으로 알 수 있는 정보라면 중복 정보가 아닐까 생각이 드는데 어떠신가요?

2024-10-23 14:30 UTC, ww8007 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +  hashtags?: TagType[];
명칭만 보면 boolean의 타입일 것 같은데 조금 혼동이 올 수 있을거 같아요
tags가 오히려 어떨까요?

2024-10-23 14:30 UTC, ww8007 commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> -      </span>
현재 코드는 가격이 0원일 경우에는 렌더링이되지 않을 것 같아요
0원인 제품이 있는 경우도 고려가 되면 어떨까요?

2024-10-28 08:11 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/participate/ParticipateButton.tsx
> +  applyStatus: boolean;
해당 부분 담당하는 백엔드 분과 이야기해서 변경 완료했습니다!

2024-10-28 08:13 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +}
추후 필요할 일이 생길 것 같아 미리 생성해 두었는데, 당장은 필요하지 않을 것 같아서 삭제하겠습니다!

2024-10-28 09:24 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
page 코드가 너무 길어져서 메뉴와 관련된 훅들을 따로 모아 놓으려고 미리 분리해 두었는데, 
분리할 만한 부분이 생각보다 많지 않아서 이렇게 되었네용.... 
다시 page 쪽으로 합쳐 놓겠습니다.

2024-11-05 16:23 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +}> = ({productData, sectionRef}) => {
명확한 이유가 있었던 건 아니고, 그냥 사용하면 편하다는 인식만 있어서 자주 사용하게 된 것 같습니다…. 
FC 사용한 부분 전부 수정해 두었고, 이번 기회에 FC 사용을 지양해야 하는 이유에 대해서도 찾아보고 공부하게 되었습니다. 감사합니당.

2024-11-05 16:25 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/share-product-link/ShareModal.tsx
> +                  src='https://i.ibb.co/MDMTKFq/insta.png'
이 부분 스토리북 컴포넌트 쪽에서 svg로 추가한 뒤 사용하려고 했는데, 인스타 svg를 불러오는 과정에서 계속해서 파일이 깨지는 바람에 추후 수정하려고 임시로 넣어두었습니다. 임시 표기 추가해 두겠습니다!

2024-11-05 16:25 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +  }, [isOpen]);
모달이 띄워진 경우에 뒤쪽 화면이 스크롤되는 걸 막는 부분인데 혹시 다른 방법도 있을까요?

2024-11-05 16:26 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/shared/ui/divider/Divider.tsx
> +import React from 'react';
필요하지 않을 것 같아서 삭제했습니다!

2024-11-05 17:00 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/shared/ui/divider/Divider.tsx
> +export {Divider};
헉 생각을 못했네요.... 수정했습니다!

2024-11-05 17:03 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +};
해당 페이지에서는 당장 레이아웃이 필요하지 않을 것 같아 삭제했습니다.

2024-11-05 17:07 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +// 이미지, 타이틀, 가격
위쪽 상품 타입에 대한 주석이 아닌 아래의 Product Main Section의 내용에 관련된 주석입니다!
다른 분들이 보시기엔 메인 섹션에서 어떤 컨텐츠를 포함하고 있는지 한눈에 알아보기 어려울 것 같아서 작성해 두었습니다.

2024-11-05 17:46 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +export default function RootLayout({children}: LayoutProps) {
수정 커밋 남겨주시면 감사하겠습니다!!

2024-11-05 18:46 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/widgets/product-image-list/ProductImageList.tsx
> +export default ProductImageList;
export로만 작성되어 있던 파일 변경했습니다!

2024-11-05 19:01 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoMenu.tsx
> +      style={{scrollbarWidth: 'none'}}
tailwind 자체에서 스크롤바와 관련된 기능은 지원하지 않고 있어서 style을 추가적으로 작성하는 방식으로 진행했는데, 찾아보니 tailwind scrollbar hide 플러그인이 따로 존재해서 style 부분 삭제 후 className에 `scrollbar-hide` 속성 추가하는 쪽으로 변경해 두었습니다!

2024-11-05 19:37 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/layout.tsx
> +export default function RootLayout({children}: LayoutProps) {
https://github.com/Wraffle-Inc/wraffle/pull/28#discussion_r1818545144
이 부분에서 따로 말씀 드리고 레이아웃 삭제했습니다!!!!!!!!

2024-11-05 20:17 UTC, Ajeong-Im commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> +  hashtags?: TagType[];
래플 카드 관련한 수정 사항들은 다른 PR에서 진행하려고 합니다!
해당 내용들 백로그에 작성해 두었습니다.

2024-11-05 20:23 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +  }, [selectedMenu]);
5c8ad10e6cc1a0d20b69e4c60e2c86b590fe4ae7
이렇게 변경했는데, 의도하신 내용이 맞을까요?

2024-11-05 20:25 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/shared/util/formatDate.ts
> +};
b02fc703576f0eacd9522d44bcb44962443ab51a
말씀해 주신대로 day js 사용해서 
제 페이지에서 사용되는 형식을 기본 포맷으로 지정했고,
다른 방식으로 사용되는 경우에 대한 예시도 주석으로 함께 작성해 놓았습니다!

2024-11-10 15:16 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
useMenu를 따로 훅으로 분리한 이유에 대한 설명이 되지 않았습니다!!
`const [selectedMenu, setSelectedMenu] = useState<string>('상품')`
를 그냥 사용했을 때와  `useMenu` 를 비교했을 때 어떤점을 고려해서 따로 커스텀훅으로 만드신건가요???

2024-11-11 20:35 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogDescription>
DialogDescription이 기본적으로 p 태그로 이루어져 있어서 발생하는 것 같아서 p 태그 삭제하고, Image 태그는 DialogDescription 밖으로 분리해서 해결했습니다!
DialogTrigger 사용하는 방법이 헷갈려서 당시에 사용하지 않았는데, 이것도 사용하는 쪽으로 코드 수정해 두었습니다. 
c82f993f45551ccbcedf5ca9f463089b3f799cfa

2024-11-11 20:50 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
`래플/이벤트 상세 페이지`와` 내가 생성한 래플/이벤트 관리 페이지`에서 공통으로 사용되기 때문에 커스텀훅으로 만드는 게 좋을 것 같다고 생각해서 작성했습니다!
현재는 page쪽으로 코드를 합쳐 놓은 상태인데, 
이 경우에는 말씀하신 대로 `const [selectedMenu, setSelectedMenu] = useState<string>('상품')`을 그냥 사용해도 괜찮을 것 같네용. 혹시 widget/product-info에 hook 폴더를 추가해서 커스텀훅을 유지하는 게 좋을까요, 아니면 단순히 useState만 사용하는 쪽으로 변경하는 게 좋을까요??

2024-11-14 10:42 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
따로 커스텀훅으로 분리했을 때 이점은 `useMenu`로 이름을 지어서 menu를 관리하는 훅이구나에 대한 가독성이 올라가는점만 떠올라서, 만약 저는(단순한 생각이니 참고정도만 해주시면 감사하겠습니다) 우선 그냥 따로 구현하고, `이벤트 상세`와 `내가 생성한 래플/이벤트 페이지`의 화면에 동일한 부분이 많다고 느껴져서 불편함을 느끼면 필요시 공통컴포넌트로 빼서 두 페이지를 구분지을 수 있는걸로 구분되도록 할거 같은데, 방법은 아정님 편하신 방법으로 진행하시면 될것 같습니다!

2024-11-18 18:57 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/product-menu/useMenu.ts
현 시점에서 해당 페이지 하나에서만 사용된다면 말씀해 주신 대로 useState를 직접 사용하는 것이 더 좋은 접근이라고 생각하지만, 다른 분과도 고민해 봤을 때 페이지 여러 개에서 사용된다면 useMenu로 분리하는 쪽이 작업할 때 좀 더 수월할 것 같다고 결론을 지어서 그렇게 작업해 두었습니다! 
의견 감사합니다. 추가적인 개선 사항이 있다면 언제든 말씀해 주세요!
6d142973be258c67661b1d25d4aaf4e6a4522302

2024-11-18 19:04 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/participate/ApplyCompleteModal.tsx
> +          </DialogDescription>
DialogDescription 내부에 이미지 태그가 존재하는 경우 hydration 에러가 발생해서, 그냥 use-dialog 훅을 사용하지 않는 쪽으로 코드 작성했습니다...

2024-11-19 13:09 UTC, eric-hjh reviewed
잔잔한 부분들 리뷰 남겼습니다!
그리고 코드가 통일되면 더 좋을 거 같아요!
ex) 어떤 파일에선 useState 타입이 선언되어 있고, 어떤 파일에서는 선언 안 되어있고 or import 해 오는 방식

2024-11-19 13:09 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +            <Header.BackButton onClick={router.back} />
BackButton에서 default onClick이 router.back이어서 없어도 될거 같습니다!

2024-11-19 13:09 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +import {ProductEventSection} from '@/widgets/product-info/ui/ProductInfoSection';
직접 불러오는 거랑 barrel files를 사용해서 불러오는 거랑 섞여있습니다! 통일되면 좋을 거 같아요!

2024-11-19 13:09 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/share-product-link/ShareDialog.tsx
> +  }, []);
어떤거 때문에 존재하는걸까요?

2024-11-19 13:09 UTC, eric-hjh commented on apps/front/wraffle-webview/src/entities/product/product.ts
> +  tags: Tag[];
tags가 중복된거 같습니다!

2024-11-20 13:41 UTC, Ajeong-Im commented on packages/ui/src/ui/raffle-card/RaffleCard.tsx
> -      </span>
위코멘트와동일합니다

2024-11-20 13:51 UTC, ww8007 approved these changes
LGTM!

2024-11-27 11:56 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/entities/product/product.ts
> +  tags: Tag[];
이 부분 삭제했습니다! 다만 추후 래플쪽 데이터가 수정될 가능성을 위해 형식은 그대로 유지했습니다.

2024-11-27 11:57 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/features/share-product-link/ShareDialog.tsx
> +  }, []);
dialog가 열려 있을 때 페이지 스크롤 방지용입니다! 스토리북 컴포넌트를 사용하는 경우에는 필요가 없어서 다른 코드에서는 삭제해 두었는데, ShareDialog에서는 지우는 걸 까먹었네요. 알려주셔서 감사합니당.

2024-11-27 11:57 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +            <Header.BackButton onClick={router.back} />
삭제했습니다!

2024-11-27 11:58 UTC, Ajeong-Im commented on apps/front/wraffle-webview/app/products/[productId]/page.tsx
> +import {ProductEventSection} from '@/widgets/product-info/ui/ProductInfoSection';
이부분 아직 논의 중인 걸로 알아서, 결정된다면 추가 이슈 생성해서 다른 코드들이랑 한번에 통일하도록 하겠습니다!

2024-11-27 12:04 UTC, eric-hjh approved these changes
LGTM! 고생하셨씁니다!

2024-11-27 12:07 UTC, merged