[WRFE-15] 래플/이벤트 생성 페이지
Wraffle-Inc/wraffle pull request #36
Opened 2024-09-29 20:30 UTC by eric-hjh

## 📖 개요

## 💻 작업사항

- 래플/이벤트 생성 페이지 작업 진행중
- 이벤트 생성 페이지 폴더구조 고민

## 💡 작성한 이슈 외에 작업한 사항

- ReactQueryProviders 폴더구조 변경

- DS 수정 
  - input field : w-full 추가
  - select : w-full, justify-between, onChange 추가
  - calendar : export 변경, CalendarIcon text-black 추가
  - tag : tag remove 함수 props 추가, 주석으로 내용 설명

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-10-04 09:40 UTC, gyeong3un2 requested changes
LGTM! 👍

궁금한 사항 몇 개 코멘트로 남겨뒀습니다!
만약 리뷰가 조금 이상하거나 이해가 안 가신다 생각드시면, 다시 review 요청 남겨주세요!

고생하셨습니다! 😁

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/app/products/create/page.tsx
> +  const funnel = useFunnel<{
퍼널에서 단계별 타입을 지정할 때, Props의 각각 타입은 같은데 optional인지 아닌지가 달라서 타입이 이렇게 선언된 것 같아요.
혹시 이렇게 지정하신 이유가 있나요?

optional이 문제라면 `Partial`을 이용해보는 건 어떨까요??

참고자료: [TypeScript Partial 타입](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype)

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/app/products/create/success/page.tsx
> +  const isReview = false;
코드를 봤을 때 래플 생성을 요청하고 검토를 받아야 해서 `isReview`라고 변수명을 지으신 것 같아요!
그런데 제가 코드를 딱 처음봤을 때, 리뷰인지 아닌지가 느껴지는 것 같아요!

그래서 변수명을 조금만 더 명확하게 수정하는 건 어떨까요?
ex) `isRequestSubmitted`나 `isPendingApproval` 과 같은 승인을 기다리고 있을 떄의 상태를 나타내면 어떨까요??

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +          items={[
이 item은 따로 상수 분리해서 관리하면 좋을 것 같아요!
래플 카테고리라면 다른 곳에서도 동일하게 사용할 것 같아서요!

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/shared/ui/progress/Progress.tsx
> +    <div className={'h-0.5 w-full bg-[#F4F4F5]'}>
이 코드에서는 중괄호를 제거해도 될 것 같아요!

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +    if (e.key === 'Enter' && !e.nativeEvent.isComposing && tag.trim() !== '') {
현재 코드에서 `handleAddTag` 함수의 조건문은 'Enter' 키를 눌렀는지, 한글을 입력 중인지, 그리고 태그가 빈 값이 아닌지를 확인하고 있습니다.
이 세 가지 조건을 하나의 조건문으로 처리하면, 코드가 복잡해지고 이해하기 어려울 수 있을 것 같습니다!

이를 관심사 분리하는 것은 어떨까요??

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +    setTags(tags.filter(tag => tag !== tagToRemove));
이렇게 상태를 업데이트하는 것도 유효하지만, 상태 업데이트가 이전 상태에 의존하는 경우 `prev`를 사용하는 것이 더 안전하고 명확할 것 같습니다!
그러면 상태 업데이트가 비동기적으로 이루어질 떄도 최신 상태를 기반으로 안전하게 업데이트할 수 있을 것 같아요!

```
ex) setState((prev) => prev.filter( ... ));
```

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +          onClick={() => onNext(title, category, tags, entries)}
이건 장현님이 추후에 추가하시려고 했을 수도 있는데, 말씀드려요!

현재 단계에서 필수로 입력해야 되는 값들을 입력 안 했다면, 체크하고 넘어가는게 좋지 않을까 싶이요!
그래서 입력 필드의 유효성을 검사한 후 valid하다면 그때 넘어가도록 구현하면 좋을 것 같아요.

2024-10-04 09:40 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
래플 생성할 때의 모든 단계를 `CreateList` 에 전부 쓰신 이유가 있나요??

이건 제 개인적인 의견이긴 한데, 한 파일에 300줄이 넘게 있으면 가독성이 떨어지기도 하고 유지보수도 힘들어서..
각 단계별로 컴포넌트 쪼개서 파일 만들어도 괜찮을 것 같아요!

2024-10-04 09:40 UTC, gyeong3un2 commented on packages/ui/src/ui/calendar/Calendar.tsx
> +export const CalendarForm = ({
`Calendar`가 현재 날짜를 선택하고 영역 밖을 선택해야 닫히는 것 같아요!
날짜를 선택했을 때 닫히게 하면 어떨까요?

모바일로 보는 유저 입장에서 약간 불편할 수도 있을 것 같아요!

2024-10-04 09:40 UTC, gyeong3un2 commented on packages/ui/src/ui/calendar/Calendar.tsx
> +export const CalendarForm = ({
추가로 현재 Calendar Storybook이 에러 나는 것 같습니다!
`const`가 default로 지정되지 않아서 import할 떄 아래와 같이 사용하셔서 에러가 나는 것 같습니다.
확인 부탁드립니다!

```
import CalendarForm from './Calendar';
```

2024-10-07 08:53 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
앗 이부분은 작업하면서 파일나누기전에 임시로 한곳에 몰아넣었었는데, 지금은 나눠놨습니다! 😀

2024-10-07 08:53 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +    if (e.key === 'Enter' && !e.nativeEvent.isComposing && tag.trim() !== '') {
리뷰 반영하여 수정해보겠습니다!

2024-10-07 08:53 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +          onClick={() => onNext(title, category, tags, entries)}
추가하여 올릴예정입니다!

2024-10-23 17:36 UTC, eric-hjh commented on packages/ui/src/ui/calendar/Calendar.tsx
> +export const CalendarForm = ({
https://github.com/Wraffle-Inc/wraffle/pull/36/commits/4e4969cc992b7dfc19305c98f4ed33fc630f7684

수정하였습니다!

2024-10-23 17:37 UTC, eric-hjh commented on packages/ui/src/ui/calendar/Calendar.tsx
> +export const CalendarForm = ({
https://github.com/Wraffle-Inc/wraffle/pull/36/commits/4e4969cc992b7dfc19305c98f4ed33fc630f7684

수정하였습니다!

2024-10-23 17:38 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +    setTags(tags.filter(tag => tag !== tagToRemove));
[apps/front/wraffle-webview/src/widgets/product-list/create/ui/TitleStepList.tsx](https://github.com/Wraffle-Inc/wraffle/pull/36/commits/23f8feaa06d95e75d473b95851df39cb0e707a97#diff-e320c19c73705138e2c1e9289e470ad58a01e48078b7a6f723544309b22082ff)

tag 조회 api연동할 때, 수정해야 할 로직인거 같아서 제거하고 api 연동할 때 구현하려 합니다!

2024-10-23 17:39 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +    if (e.key === 'Enter' && !e.nativeEvent.isComposing && tag.trim() !== '') {
[apps/front/wraffle-webview/src/widgets/product-list/create/ui/TitleStepList.tsx](https://github.com/Wraffle-Inc/wraffle/pull/36/commits/23f8feaa06d95e75d473b95851df39cb0e707a97#diff-e320c19c73705138e2c1e9289e470ad58a01e48078b7a6f723544309b22082ff)

tag 조회 api연동할 때, 수정해야 할 로직인거 같아서 제거하고 api 연동할 때 구현하려 합니다!

2024-10-23 17:40 UTC, eric-hjh commented on apps/front/wraffle-webview/src/shared/ui/progress/Progress.tsx
> +    <div className={'h-0.5 w-full bg-[#F4F4F5]'}>
https://github.com/Wraffle-Inc/wraffle/pull/36/commits/a950f3f7add2478cb481c00d6e9dfb195e31f903

수정하였습니다!

2024-10-23 17:42 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/ui/CreateList.tsx
> +          items={[
https://github.com/Wraffle-Inc/wraffle/pull/36/commits/23f8feaa06d95e75d473b95851df39cb0e707a97#diff-e320c19c73705138e2c1e9289e470ad58a01e48078b7a6f723544309b22082ff

조회 api 연동 후 삭제될 코드 입니다. categoryItems, tags

2024-10-23 17:43 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/create/success/page.tsx
> +  const isReview = false;
오딜런 : '일단 미검토 플로우로 진행하려합니당'
 로 되면서 삭제하였습니다.

2024-11-04 08:59 UTC, sangminlee98 approved these changes
개인적으로 entities 레이어는 비즈니스 엔티티를 정의하는 레이어라고 생각해서 model이나 api 호출 코드를 배치하는게 더 어울릴 것 같고, features 레이어에서 비즈니스 로직이나 ui 컴포넌트들을 배치하는게 더 어울릴 것 같다고 생각이 드는데 @ww8007 혹시 어떻게 생각하시나요??

2024-11-04 08:59 UTC, sangminlee98 commented on apps/front/wraffle-webview/app/products/create/event/page.tsx
> +  .build();
`createFunnelSteps`로 스텝을 선언해서 사용하면 특정 스텝에서 requiredKey에 해당하는 값이 없을 때 해당 스텝에 접근하지 못하는건가요?!

2024-11-04 08:59 UTC, sangminlee98 commented on apps/front/wraffle-webview/src/entities/product-form/ui/PriceForm.tsx
> +                placeholder='응모 금액을 입력해주세요.'
피그마 UI 상에서 래플의 경우에도 `응모 금액을 입력해주세요`로 표기되어 있긴 한데 래플의 경우에는 응모 금액보다는 `상품 금액`이라고 표기하는게 더 좋을 것 같아요..!

2024-11-04 16:05 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/create/event/page.tsx
> +  .build();
네 맞습니다!
use funnel의 단계별 context 정의하기 파트를 읽어보다가 
제가 느끼기에 [createFunnelSteps()으로 정의하는 법](https://use-funnel.slash.page/ko/docs/context-guide#createfunnelsteps%EC%9C%BC%EB%A1%9C-%EC%A0%95%EC%9D%98%ED%95%98%EB%8A%94-%EB%B2%95)이 가독성이 좋다 느껴져서 선택했어요!

2024-11-04 16:24 UTC, eric-hjh commented on apps/front/wraffle-webview/src/entities/product-form/ui/PriceForm.tsx
> +                placeholder='응모 금액을 입력해주세요.'
생각해보니 래플일 경우는 상품금액이 더 자연스럽겠네요! 
감사합니다!!
[73a15](https://github.com/Wraffle-Inc/wraffle/pull/36/commits/73a1547a82f7d1e373d79b2b1398287b20cb0d39)

2024-11-04 17:28 UTC, eric-hjh commented
> 개인적으로 현재 entities 레이어에 있는 UI 컴포넌트들을 features 레이어에 배치하는게 더 어울릴 것 같다고 생각이 드는데 @ww8007 혹시 어떻게 생각하시나요??

제 생각은 form부분을 entites에 배치할 때, 데이터를 받아오는거니까 데이터를 다루는 entities에 넣어야 한다 생각을 했었는데, 사용자에게 입력받아오는 역할이 주니까 샘님 의견대로 features가 더 어울릴거 같네요.
ThumbnailCard는 props 받아서 보여지는 역할만 하니까 남아있어도 될것 같고, form관련 컴포넌트는 features로 옮기는거에 동의합니다!

2024-11-05 05:03 UTC, gyeong3un2 reviewed
궁금하거나 제안하고 싶은 곳에 몇 가지 코멘트 남겼습니다!
보시고 같이 의논해봐도 좋을 것 같아요! 😁

2024-11-05 05:03 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/shared/util/const.ts
1. 상수 표현 같은 경우에는 대문자로 하고 단어와 단어사이에는 언더스코어문자(`_`)를 사용해서 선언하면 좋을 것 같습니다. 이렇게 하면 상수임을 더 명확하게 나타낼 수 있을 것 같습니다.

```
export const TITLE_LIMIT = 40;
export const TAG_LIMIT = 9;
export const PRICE_LIMIT = 11;
export const ETC_LIMIT = 400;
export const WINNER_LIMIT = 3;
```

3. 현재 이 파일은 `utils` 폴더보다는 `constants` 폴더를 생성해서 거기에 두는 게 좋을 것 같습니다!
4. 파일명을 `const`로 하신 이유가 상수 이름인 `constant`에서 따오신 것이라면, `constant/limit.ts`로 해도 괜찮을 것 같습니다!

2024-11-05 05:03 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/create/ui/DateStepList.tsx
> +  const startDate = watch('startDate');
`watch`를 쓰는 것보다 `useWatch`를 사용하는 게 성능에 더 좋다고 합니다!
그리고 여러개의 변수를 불러올 때 묶어서 사용하면 가독성이 좀 더 좋아질 것 같아요!

ex)
```
const [startDate, endDate, announceAt, winnerCount] = useWatch(
  control, 
  name: ['startDate', 'endDate', announceAt', 'winnerCount']
);
```

참고자료: [[react-hook-form] form.watch vs useWatch(성능을 위해서는 useWatch 고려)](http://itpsolver.com/react-hook-form-form-watch-vs-usewatch-%EC%84%B1%EB%8A%A5%EC%9D%84-%EC%9C%84%ED%95%B4%EC%84%9C%EB%8A%94-usewatch-%EA%B3%A0%EB%A0%A4/)

2024-11-05 05:03 UTC, gyeong3un2 commented on apps/front/wraffle-webview/src/widgets/product-list/create/ui/ProductList.tsx
> +  const products = getValues('products');
`watch`가 아닌 `getValues`를 사용하신 이유가 궁금합니다!

2024-11-05 14:20 UTC, eric-hjh commented on apps/front/wraffle-webview/src/shared/util/const.ts
저는 주로 유틸 안에 const.ts파일 안에 상수 몰아넣고 사용해와서 util/const로 생성해두었었는데, constant 아래에서 관리하면 import된걸 볼 때 파악하기 더 간편할거 같아서 좋은거 같네요!

상수 관련 컨벤션은 한번 다같이 정해보는것도 좋은거 같아요!

2024-11-05 17:07 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/create/ui/ProductList.tsx
> +  const products = getValues('products');
watch로 감시하지 않아도, 이미지 스텝에서 products를 설정한 후, 돌아와도 funnel의 상태가 변경됨에 따라 리랜더링이 일어나 새로운 products를 가져와서 getValues를 사용하였습니다.

2024-11-05 17:42 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/create/ui/DateStepList.tsx
> +  const startDate = watch('startDate');
[de5a609](https://github.com/Wraffle-Inc/wraffle/pull/36/commits/de5a609fda41191d3abd90edb44fbcf87251424a) 수정내용입니다!

2024-11-05 17:44 UTC, eric-hjh commented on apps/front/wraffle-webview/src/shared/util/const.ts
[e4fbe82](https://github.com/Wraffle-Inc/wraffle/pull/36/commits/e4fbe8246ddb8ca54fa36af9af4e6eaee21d09b3) 수정 내용입니다

2024-11-06 00:39 UTC, gyeong3un2 approved these changes
LGTM!

2024-11-06 09:58 UTC, merged