[WRFE-21](feat): firebase setting
Wraffle-Inc/wraffle pull request #39
Opened 2024-10-09 12:34 UTC by ww8007

## 📖 개요

- resolve : #21

## 💻 작업사항

- [x] : firebase setting 추가

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-10-15 16:47 UTC, sangminlee98 requested changes
아래 리뷰 내용만 반영해주시면 될 것 같아요!
패키지 설치했을때 실행 잘 됩니다 👍

2024-10-15 16:47 UTC, sangminlee98 commented on apps/front/wraffle-native/app.json
> +    ],
`@react-native-firebase/app`, `@react-native-firebase/auth`, `expo-build-properties`
세 모듈이 package.json에 명시되어 있지 않아서 expo start가 되지 않습니다!

2024-10-16 10:43 UTC, ww8007 commented on apps/front/wraffle-native/app.json
> +    ],
expo prebuild 방식을 사용하여 app.json의 내용은 필요없는 내용이 되어서 제거 하였습니다.
https://github.com/Wraffle-Inc/wraffle/pull/39/commits/62591f846828c0a5814b2d82f99c8f868c3df050

2024-10-16 14:10 UTC, sangminlee98 approved these changes
확인했습니다 👍

2024-10-17 16:21 UTC, merged