[WRFE-48] 래플/이벤트 수정 페이지
Wraffle-Inc/wraffle pull request #50
Opened 2024-10-30 11:30 UTC by eric-hjh

## 📖 개요

## 💻 작업사항

- 생성 페이지 merge되면 사용할 form들 대기중

## 💡 작성한 이슈 외에 작업한 사항

-

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-11-20 14:22 UTC, ww8007 requested changes
궁금한 점 몇개 코멘트 남겼습니다!

2024-11-20 14:22 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +}) => {
혹시 interface를 따로 선언하지 않는 이유가 따로 있으신가요?
저는 보통 
```ts
interface Params {
 id : string;
}

interface SearchParams {
 type : 'raffle' | 'event'
}

interface EditProps {
 params : Params;
 searchParams : SearchParams;
}
```
요런식으로 썼는데 interface 파일만 읽더라도 이 컴포넌트에서 대충 어느게 필요하겠구나에 대한
생각을 분리할 수 있어서 좋은 것 같았어요
이 부분에 대한 장현님의 생각은 어떠신가요?

2024-11-20 14:22 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +  };
삭제될 코드라도 매 랜더링시 마다 product 객체가 생성되는걸 고려할 때 컴포넌트 외부나
파일로 분리하는게 좋을 것 같아요!

2024-11-20 14:22 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-list/edit/ui/EditList.tsx
> +        </div>
이미지 추가하는 AddImage 컴포넌트와 Image 컴포넌트로 분리되면 어떨까요?

2024-11-20 14:22 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
외부에서 사용할 때 이 컴포넌트가 어떤 일을 하는지 파일을 열어보기 전 까지는 동작을 예측하기 어려운 코드 같아요
1. 날짜 판단
2. 토스트
3. form에 setting

useDateValidationWithToast 같은 네이밍을 가져가는 것도 좋을거 같은데 과연 form을 여기서 setting 하는게 훅의 책임이 맞는가에 대한 고민이 드네요
어떠신가요?

2024-11-20 21:18 UTC, eric-hjh reviewed
감사합니다!

2024-11-20 21:18 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +}) => {
interface를 따로 선언하지 않는 이유는 
1. 나누지 않는게 더 직관적이다 생각하고, 
2. 개인적으로 코드를 읽을 때 아래 ->위 (왼 -> 오)로 읽는게 좋아서, 
3. 코드양이 굳이 늘아난다는 느낌을 가지고 있었습니다.

인터페이스로 분리할 때는 가독성이 떨어진다 느껴질 때 (ex. props로 받아오는게 많다거나, 복잡한 관계라던가..) 분리를 해서 사용해왔었는데, 
'생각을 분리해 볼 수 있다'  와 같은 생각은 못해봤던 접근이어서 한번 생각해보겠습니다! 
(이렇게 적었는데 밑에 훅 보니까 분리해서 사용했네요 ; 3개가 많다 생각하진 않는데)

2024-11-20 21:18 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
코드 중복을 줄일 수 있는 점과 훅으로 나누긴 했지만 form을 사용하는 제한된 곳에서 사용할것이라는 생각으로 코드를 작성하여 간과한 부분인거 같아 수정하겠습니다

2024-11-26 12:53 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
하다가 궁금한점이 있는데, 이 훅의 사용이 폼 데이터 유효성을 체크하고 강제로 수정하는 것까지가 필요로 하다 하더라도 훅에서 form의 내용을 세팅하는것이 분리되는게 맞을까요?
훅 외부의 상태가 훅 내부에서 변경된다는것은 옳지 않다 라고 생각하다가 그래도 effect안에서 변경이 되어서 괜찮지 않을까 라는 생각이 들어서 궁금합니다!

2024-11-26 12:56 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/edit/ui/EditList.tsx
> +        </div>
AddImage 컴포넌트와 Image 컴포넌트 추가 커밋 : [81487ba](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/81487ba0a3c0084344f9478ff43e54293735ca4a)
refactoring 커밋 : [09e2e82](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/09e2e82f84a12099acd164fb49752b15c91187eb)
수정 커밋 입니다!

2024-11-26 12:56 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +  };
[29d6cff](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/29d6cff4799ca18c18f4558b16abe39a36e55d7d)
수정 커밋 입니다!

2024-11-26 13:18 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
[a9c6708](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/a9c6708380f4f6748e11f02a8c54dc723c8f9c84)
수정 커밋 입니다!

2024-11-29 16:08 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
저번에 의논했었던 방향에서 처음 이야기 나왔던 onChange에 조건을 거는 방향으로 생각해보다가, 처음 생각했던 흐름은 
-  오버된 날짜를 선택시 날짜를 강제로 변경 시킨 후, toast를 보여주는 방향이었는데, 

생각해보니까, 날짜를 강제로 변경하는 흐름 보단, 선택할 때 유효성에 걸리면 토스트를 보여주고, 변경을 못하는 방향이 사용자에게 더 좋은 경험이 될거 같아서 이 방향으로 수정해 보았는데, 어떠신거 같나요??
[4e1f418](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/4e1f418c83ceb03ada1272a4afafa0d5d0b3dbd3)

2024-12-04 13:37 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/product-form/config/validateDate.ts
> +export const validateDate = (
validateDate 보다는 이 날짜가 이전 날짜 보다 큰지를 보여주도록 함수 명에서 드러나면 좋을 것 같아요
`isDateBefore` 같은 느낌이 되면 어떨까요?

2024-12-04 13:39 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/product-form/ui/EndDateForm.tsx
> +              }}
ui에서 이 로직을 담당하는 것 보다는 onSelect를 외부에서 받아서 관리하는 방식이 좋아보일 것 같아요!
추후에 이 로직을 수정하기 위해서는 ui에 해당하는 이 onSelect까지 와야 한다는 사실을 알기 어려울 것 같아요

2024-12-04 13:39 UTC, ww8007 commented on apps/front/wraffle-webview/src/features/product-form/ui/StartDateForm.tsx
> +              }}
이 부분도 위와 동일 합니다!

2024-12-04 13:39 UTC, ww8007 commented on apps/front/wraffle-webview/src/widgets/product-list/lib/hooks/useDateValidation.ts
> +};
@eric-hjh 
네 저는 이 방향도 좋을 것 같습니다!

2024-12-04 13:40 UTC, ww8007 commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +}) => {
그럼 통일되는 편이 좋을 것 같아요!

2024-12-11 12:45 UTC, eric-hjh commented on apps/front/wraffle-webview/app/products/[id]/edit/page.tsx
> +}) => {
[825710c](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/825710cc61ada57c90ebf41fddc1762bafa2e1a8)
수정 커밋입니다!
다른 코드를 보았을 때, interface로 분리된 코드가 많아서 통일시키는편이 좋을거 같아서 분리시켜두었습니다!

2024-12-11 12:45 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-form/config/validateDate.ts
> +export const validateDate = (
[17b7a0f](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/17b7a0fede16280ff7d3cb109a917c00c0b0d909)
수정 커밋입니다!

2024-12-11 12:46 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-form/ui/EndDateForm.tsx
> +              }}
[1ff0234](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/1ff02341147ace4f7c994b90aaaa0bf7432d5ea7)
수정 커밋입니다!

2024-12-11 12:46 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-form/ui/StartDateForm.tsx
> +              }}
[1ff0234](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/1ff02341147ace4f7c994b90aaaa0bf7432d5ea7)
수정 커밋입니다!

2024-12-17 05:12 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-form/ui/EndDateForm.tsx
> +              }}
[e3533bc](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/e3533bcd3db43e094d07ba1fd163c623659a92b4)
수정 커밋입니다!

2024-12-17 05:12 UTC, eric-hjh commented on apps/front/wraffle-webview/src/features/product-form/ui/StartDateForm.tsx
> +              }}
[e3533bc](https://github.com/Wraffle-Inc/wraffle/pull/50/commits/e3533bcd3db43e094d07ba1fd163c623659a92b4)
수정 커밋입니다!

2024-12-31 14:53 UTC, ww8007 approved these changes
엇 그냥 머지 하셨어도 괜찮았는데 ㅠㅠ
고생하셨습니다!

2025-01-03 09:53 UTC, merged