[WRDS-45] (feat): Typo 스토리북 수정
Wraffle-Inc/wraffle pull request #51
Opened 2024-10-30 12:28 UTC by Joy0w0

## 📖 개요

- resolve : #45

## 💻 작업사항

- 변경사항 맞춰 Typo 스토리북 수정

## 💡 작성한 이슈 외에 작업한 사항

- 다른 컴포넌트 및 페이지 Typo props 수정

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-10-30 18:04 UTC, sangminlee98 requested changes
확인했습니다!
MDX 독스를 보면 이전에 사용하던 `weight`, `lineHeight`, `textColor`에 대한 설명이 남아있는데 혹시 이것도 수정해주실 수 있나요?
[typo.ts](https://github.com/Wraffle-Inc/wraffle/blob/dev/packages/ui/src/ui/typography/util/typo.ts) 참고하시면 될 것 같아요!

2024-11-06 13:58 UTC, Joy0w0 commented
> [f5537ac](https://github.com/Wraffle-Inc/wraffle/pull/51/commits/f5537ac015b5c6b750bbb11c4af580a2052f3396)
mdx 수정했습니다!

2024-11-06 14:07 UTC, ww8007 approved these changes
LGTM!

2024-11-06 14:14 UTC, sangminlee98 approved these changes
확인했습니다 👍

2024-11-13 13:45 UTC, merged