[WRFE-44](feat): 내가 생성한 래플/이벤트 페이지 퍼블리싱
Wraffle-Inc/wraffle pull request #65
Opened 2024-12-05 08:30 UTC by Ajeong-Im

## 📖 개요

- 내가 생성한 래플/이벤트 페이지 퍼블리싱

## 💻 작업사항

- 내가 생성한 래플/이벤트일 경우
  - 가격 대신 응모 인원 수 표시
  - 응모 버튼 대신 추첨 버튼 표시

- 내가 생성한 경우/아닌 경우 모두 당첨자 수 표시

## 💡 작성한 이슈 외에 작업한 사항

- next.config.mjs 파일에 image 도메인으로 `github.com` 추가 -> api 연동 후 삭제 예정

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-12-20 05:56 UTC, eric-hjh requested changes
확인했습니다!

2024-12-20 05:56 UTC, eric-hjh commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +            </button>
생성자가 아닐 때에도 수정 버튼이 보여지고 있습니다!
그리고 push할 때, [id]값도 수정 부탁드립니다!

2025-01-07 05:51 UTC, Ajeong-Im commented on apps/front/wraffle-webview/src/widgets/product-info/ui/ProductInfoSection.tsx
> +            </button>
수정 완료했습니다!
29ee68c6b70066e76fa072ac6f2b5e991eb0d09b

2025-01-07 07:05 UTC, eric-hjh approved these changes
LGTM!

2025-01-07 07:05 UTC, merged